@startuml
set separator none

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  componentStyle uml1
}

hide stereotype

skinparam component<<Modules.Modules.commonnotification>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam component<<Modules.Modules.customerprofileevent>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam component<<Modules.Modules.productcatalogevent>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Modules.Modules>> {
  BorderColor #9a9a9a
  FontColor #9a9a9a
  shadowing false
}

component "==customer-profile-event\n<size:10>[Component: Module]</size>" <<Modules.Modules.customerprofileevent>> as Modules.Modules.customerprofileevent
component "==common-notification\n<size:10>[Component: Module]</size>" <<Modules.Modules.commonnotification>> as Modules.Modules.commonnotification
component "==product-catalog-event\n<size:10>[Component: Module]</size>" <<Modules.Modules.productcatalogevent>> as Modules.Modules.productcatalogevent
Modules.Modules.commonnotification .[#707070,thickness=2].> Modules.Modules.productcatalogevent : "<color:#707070>listens to"
Modules.Modules.commonnotification .[#707070,thickness=2].> Modules.Modules.customerprofileevent : "<color:#707070>listens to"
@enduml