@startuml
set separator none

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  componentStyle uml1
}

hide stereotype

skinparam component<<Modules.Modules.partnermanagementinternal>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam component<<Modules.Modules.productmanagementapi>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Modules.Modules>> {
  BorderColor #9a9a9a
  FontColor #9a9a9a
  shadowing false
}

component "==product-management-api\n<size:10>[Component: Module]</size>" <<Modules.Modules.productmanagementapi>> as Modules.Modules.productmanagementapi
component "==partner-management-internal\n<size:10>[Component: Module]</size>" <<Modules.Modules.partnermanagementinternal>> as Modules.Modules.partnermanagementinternal
Modules.Modules.partnermanagementinternal .[#707070,thickness=2].> Modules.Modules.productmanagementapi : "<color:#707070>uses"
@enduml