<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sktelecom.nova</groupId>
        <artifactId>nova-service</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>nova-sba-monolith</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>com.sktelecom.nova</groupId>-->
<!--            <artifactId>nova-product-catalog-internal</artifactId>-->
<!--            <scope>runtime</scope>-->
<!--            <version>1.0-SNAPSHOT</version>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>com.sktelecom.nova</groupId>-->
<!--            <artifactId>nova-product-pricing-api</artifactId>-->
<!--            <scope>runtime</scope>-->
<!--            <version>1.0-SNAPSHOT</version>-->
<!--        </dependency>-->

        <dependency>
            <groupId>com.sktelecom.nova</groupId>
            <artifactId>nova-product-catalog-internal</artifactId>
            <scope>runtime</scope>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.sktelecom.nova</groupId>
            <artifactId>nova-product-pricing-internal</artifactId>
            <scope>runtime</scope>
            <version>1.0-SNAPSHOT</version>
        </dependency>


        <dependency>
            <groupId>com.sktelecom.nova</groupId>
            <artifactId>nova-customer-profile-internal</artifactId>
            <scope>runtime</scope>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.sktelecom.nova</groupId>
            <artifactId>nova-customer-subscription-internal</artifactId>
            <scope>runtime</scope>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.sktelecom.nova</groupId>
            <artifactId>nova-common-notification-internal</artifactId>
            <scope>runtime</scope>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.3.0</version>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.4.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>